# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
    build:
        docker:
            - image: gcc:latest
        working_directory: ~/work
        steps:
            - checkout
            - run: cmake ..
            - run: make
            - run: ./a.out
