# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
    build:
        docker:
            - image: 0uts1de/gcc-cmake:latest
        working_directory: ~/Aluminium
        steps:
            - checkout
            - run: mkdir build
            - run: cd build
            - run: cmake ..
            - run: make
            - run: ./a.out
